# Generated by Django 4.2 on 2023-04-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('EUR', models.DecimalField(decimal_places=2, max_digits=5)),
                ('USD', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
